[2025-06-24T00:02:27.607+0700] {processor.py:161} INFO - Started process (PID=5815) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:02:27.608+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:02:27.611+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:02:27.611+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:02:27.615+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:02:27.614+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:02:27.615+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:02:27.615+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:02:27.616+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:02:27.627+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2025-06-24T00:03:21.630+0700] {processor.py:161} INFO - Started process (PID=6291) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:03:21.632+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:03:21.635+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:03:21.634+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:03:21.639+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:03:21.638+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:03:21.639+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:03:21.639+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:03:21.640+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:03:21.655+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-06-24T00:04:18.065+0700] {processor.py:161} INFO - Started process (PID=6800) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:04:18.070+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:04:18.073+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:04:18.072+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:04:18.076+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:04:18.076+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:04:18.077+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:04:18.077+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:04:18.077+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:04:18.090+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-06-24T00:05:07.551+0700] {processor.py:161} INFO - Started process (PID=6976) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:05:07.556+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:05:07.558+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:05:07.558+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:05:07.563+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:05:07.562+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:05:07.563+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:05:07.563+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:05:07.563+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:05:07.578+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-06-24T00:07:34.766+0700] {processor.py:161} INFO - Started process (PID=8200) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:07:34.771+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:07:34.772+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:07:34.771+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:07:34.775+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:07:34.775+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:07:34.776+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:07:34.776+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:07:34.776+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:07:34.791+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-06-24T00:08:59.426+0700] {processor.py:161} INFO - Started process (PID=10729) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:08:59.429+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:08:59.430+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:08:59.429+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:08:59.434+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:08:59.433+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:08:59.434+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:08:59.434+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:08:59.435+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:08:59.450+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-06-24T00:09:51.499+0700] {processor.py:161} INFO - Started process (PID=10870) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:09:51.502+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:09:51.503+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:09:51.502+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:09:51.507+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:09:51.507+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:09:51.508+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:09:51.508+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:09:51.508+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:09:51.523+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-06-24T00:10:46.057+0700] {processor.py:161} INFO - Started process (PID=11081) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:10:46.059+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:10:46.061+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:10:46.060+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:10:46.064+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:10:46.064+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:10:46.065+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:10:46.065+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:10:46.065+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:10:46.077+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2025-06-24T00:11:57.956+0700] {processor.py:161} INFO - Started process (PID=12529) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:11:57.961+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:11:57.962+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:11:57.962+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:11:57.966+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:11:57.966+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:11:57.967+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:11:57.967+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:11:57.967+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:11:57.979+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-06-24T00:13:02.356+0700] {processor.py:161} INFO - Started process (PID=12748) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:13:02.361+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:13:02.362+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:13:02.361+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:13:02.366+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:13:02.366+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:13:02.366+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:13:02.366+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:13:02.367+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:13:02.381+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-06-24T00:13:53.880+0700] {processor.py:161} INFO - Started process (PID=12932) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:13:53.884+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:13:53.885+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:13:53.885+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:13:53.889+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:13:53.889+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:13:53.890+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:13:53.889+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:13:53.890+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:13:53.902+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2025-06-24T00:15:00.047+0700] {processor.py:161} INFO - Started process (PID=13286) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:15:00.052+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:15:00.053+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:15:00.053+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:15:00.057+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:15:00.056+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:15:00.057+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:15:00.057+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:15:00.058+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:15:00.071+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-06-24T00:21:44.733+0700] {processor.py:161} INFO - Started process (PID=16625) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:21:44.738+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:21:44.740+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:21:44.739+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:21:44.743+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:21:44.743+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:21:44.744+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:21:44.744+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:21:44.744+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:21:44.758+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2025-06-24T00:22:36.644+0700] {processor.py:161} INFO - Started process (PID=16895) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:22:36.650+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:22:36.651+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:22:36.651+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:22:36.655+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:22:36.655+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:22:36.656+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:22:36.655+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:22:36.656+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:22:36.669+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-06-24T00:33:56.719+0700] {processor.py:161} INFO - Started process (PID=20304) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:33:56.724+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:33:56.725+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:33:56.725+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:33:56.729+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:33:56.729+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:33:56.730+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:33:56.730+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:33:56.730+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:33:56.745+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-06-24T00:34:50.395+0700] {processor.py:161} INFO - Started process (PID=20450) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:34:50.401+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:34:50.403+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:34:50.402+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:34:50.407+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:34:50.406+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:34:50.408+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:34:50.407+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:34:50.408+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:34:50.423+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2025-06-24T00:35:43.772+0700] {processor.py:161} INFO - Started process (PID=20592) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:35:43.777+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:35:43.778+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:35:43.778+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:35:43.782+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:35:43.782+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:35:43.783+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:35:43.782+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:35:43.783+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:35:43.797+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-06-24T00:36:52.445+0700] {processor.py:161} INFO - Started process (PID=21052) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:36:52.447+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:36:52.448+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:36:52.447+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:36:52.452+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:36:52.451+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:36:52.452+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:36:52.452+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:36:52.453+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:36:52.466+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2025-06-24T00:52:54.810+0700] {processor.py:161} INFO - Started process (PID=25176) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:52:54.815+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:52:54.816+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:52:54.815+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:52:54.820+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:52:54.820+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:52:54.821+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:52:54.821+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:52:54.821+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:52:54.837+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-06-24T00:53:48.293+0700] {processor.py:161} INFO - Started process (PID=25376) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:53:48.294+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:53:48.295+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:53:48.295+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:53:48.298+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:53:48.298+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:53:48.298+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:53:48.298+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:53:48.299+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:53:48.310+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2025-06-24T00:54:41.603+0700] {processor.py:161} INFO - Started process (PID=25671) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:54:41.609+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T00:54:41.611+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:54:41.610+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:54:41.615+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:54:41.614+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T00:54:41.616+0700] {logging_mixin.py:188} INFO - [2025-06-24T00:54:41.615+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T00:54:41.616+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T00:54:41.631+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2025-06-24T01:03:30.492+0700] {processor.py:161} INFO - Started process (PID=28615) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T01:03:30.494+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T01:03:30.496+0700] {logging_mixin.py:188} INFO - [2025-06-24T01:03:30.495+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T01:03:30.500+0700] {logging_mixin.py:188} INFO - [2025-06-24T01:03:30.499+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T01:03:30.500+0700] {logging_mixin.py:188} INFO - [2025-06-24T01:03:30.500+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T01:03:30.501+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T01:03:30.515+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2025-06-24T01:04:23.413+0700] {processor.py:161} INFO - Started process (PID=28860) to work on /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T01:04:23.418+0700] {processor.py:830} INFO - Processing file /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-06-24T01:04:23.419+0700] {logging_mixin.py:188} INFO - [2025-06-24T01:04:23.418+0700] {dagbag.py:540} INFO - Filling up the DagBag from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T01:04:23.423+0700] {logging_mixin.py:188} INFO - [2025-06-24T01:04:23.422+0700] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-06-24T01:04:23.423+0700] {logging_mixin.py:188} INFO - [2025-06-24T01:04:23.423+0700] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-06-24T01:04:23.423+0700] {processor.py:842} WARNING - No viable dags retrieved from /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-06-24T01:04:23.437+0700] {processor.py:183} INFO - Processing /home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
