[2025-06-22T16:25:25.962+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-22T16:25:25.982+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_kafka_hadoop_and_run_notebooks.start_zookeeper manual__2025-06-22T09:25:23.883265+00:00 [queued]>
[2025-06-22T16:25:25.987+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_kafka_hadoop_and_run_notebooks.start_zookeeper manual__2025-06-22T09:25:23.883265+00:00 [queued]>
[2025-06-22T16:25:25.987+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2025-06-22T16:25:26.008+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_zookeeper> on 2025-06-22 09:25:23.883265+00:00
[2025-06-22T16:25:26.012+0700] {standard_task_runner.py:63} INFO - Started process 14417 to run task
[2025-06-22T16:25:26.017+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'start_kafka_hadoop_and_run_notebooks', 'start_zookeeper', 'manual__2025-06-22T09:25:23.883265+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/start_DAG.py', '--cfg-path', '/tmp/tmp_kv1hcs1']
[2025-06-22T16:25:26.018+0700] {standard_task_runner.py:91} INFO - Job 25: Subtask start_zookeeper
[2025-06-22T16:25:26.051+0700] {task_command.py:426} INFO - Running <TaskInstance: start_kafka_hadoop_and_run_notebooks.start_zookeeper manual__2025-06-22T09:25:23.883265+00:00 [running]> on host Panda
[2025-06-22T16:25:26.110+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='group_03' AIRFLOW_CTX_DAG_ID='start_kafka_hadoop_and_run_notebooks' AIRFLOW_CTX_TASK_ID='start_zookeeper' AIRFLOW_CTX_EXECUTION_DATE='2025-06-22T09:25:23.883265+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-22T09:25:23.883265+00:00'
[2025-06-22T16:25:26.111+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-22T16:25:26.112+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-22T16:25:26.112+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        cd /home/panda/kafka_2.13-3.9.1 &&         nohup bin/zookeeper-server-start.sh config/zookeeper.properties > /tmp/zookeeper.log 2>&1 &\n        ']
[2025-06-22T16:25:26.124+0700] {subprocess.py:86} INFO - Output:
[2025-06-22T16:33:05.168+0700] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-06-22T16:33:05.169+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-22T16:33:05.181+0700] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 14417. PIDs of all processes in the group: [14418, 14417]
[2025-06-22T16:33:05.182+0700] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 14417
[2025-06-22T16:33:05.182+0700] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-22T16:33:05.183+0700] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-06-22T16:33:05.183+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-22T16:33:05.234+0700] {process_utils.py:80} INFO - Process psutil.Process(pid=14417, status='terminated', exitcode=0, started='16:25:25') (14417) terminated with exit code 0
[2025-06-22T16:33:05.235+0700] {process_utils.py:80} INFO - Process psutil.Process(pid=14418, status='terminated', started='16:25:25') (14418) terminated with exit code None
