[2025-06-24T01:04:37.017+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-24T01:04:37.045+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: start_kafka_hadoop_and_run_notebooks.start_zookeeper manual__2025-06-23T18:04:34.811000+00:00 [queued]>
[2025-06-24T01:04:37.050+0700] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: start_kafka_hadoop_and_run_notebooks.start_zookeeper manual__2025-06-23T18:04:34.811000+00:00 [queued]>
[2025-06-24T01:04:37.050+0700] {taskinstance.py:2303} INFO - Starting attempt 1 of 4
[2025-06-24T01:04:37.063+0700] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): start_zookeeper> on 2025-06-23 18:04:34.811000+00:00
[2025-06-24T01:04:37.068+0700] {standard_task_runner.py:63} INFO - Started process 28988 to run task
[2025-06-24T01:04:37.072+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'start_kafka_hadoop_and_run_notebooks', 'start_zookeeper', 'manual__2025-06-23T18:04:34.811000+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/start_DAG.py', '--cfg-path', '/tmp/tmptaa54n1r']
[2025-06-24T01:04:37.073+0700] {standard_task_runner.py:91} INFO - Job 38: Subtask start_zookeeper
[2025-06-24T01:04:37.115+0700] {task_command.py:426} INFO - Running <TaskInstance: start_kafka_hadoop_and_run_notebooks.start_zookeeper manual__2025-06-23T18:04:34.811000+00:00 [running]> on host Panda
[2025-06-24T01:04:37.188+0700] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='group_03' AIRFLOW_CTX_DAG_ID='start_kafka_hadoop_and_run_notebooks' AIRFLOW_CTX_TASK_ID='start_zookeeper' AIRFLOW_CTX_EXECUTION_DATE='2025-06-23T18:04:34.811000+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-23T18:04:34.811000+00:00'
[2025-06-24T01:04:37.189+0700] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-24T01:04:37.190+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-24T01:04:37.191+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bash -c "cd /home/panda/kafka_2.13-3.9.1 && nohup bin/zookeeper-server-start.sh config/zookeeper.properties > /tmp/zookeeper.log 2>&1 & sleep 5"']
[2025-06-24T01:04:37.205+0700] {subprocess.py:86} INFO - Output:
[2025-06-24T01:05:30.091+0700] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-24T01:05:30.092+0700] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-06-24T01:05:30.093+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-24T01:05:30.105+0700] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/operators/bash.py", line 234, in execute
    result = self.subprocess_hook.run_command(
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 91, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/home/panda/Documents/ODAP/Project/venv310/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-06-24T01:05:30.109+0700] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=start_kafka_hadoop_and_run_notebooks, task_id=start_zookeeper, execution_date=20250623T180434, start_date=20250623T180437, end_date=20250623T180530
